# Generated by Django 3.2.9 on 2021-12-02 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='price',
        ),
        migrations.AddField(
            model_name='quantitymaterial',
            name='price',
            field=models.IntegerField(default=0, help_text='Укажите цену материала', validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Цена материала'),
        ),
        migrations.AlterField(
            model_name='quantitymaterial',
            name='quantity',
            field=models.IntegerField(help_text='Укажите колличество материала', validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Колличество материала'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение: 1')], verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_quantity', to='estimate.work', verbose_name='Наименование работ'),
        ),
    ]
