# Generated by Django 3.2.9 on 2021-12-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_auto_20211202_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantitymaterial',
            options={'verbose_name': 'Материал/цена/колличество', 'verbose_name_plural': 'Материал/цена/колличество'},
        ),
        migrations.AlterModelOptions(
            name='quantitywork',
            options={'verbose_name': 'Работы/цена/колличество', 'verbose_name_plural': 'Работы/цена/колличество'},
        ),
        migrations.AddField(
            model_name='quantitywork',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
