# Generated by Django 3.2.9 on 2021-12-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0003_auto_20211202_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitymaterial',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
    ]
