# Generated by Django 3.2.9 on 2022-01-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0004_auto_20220110_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Дополнительные файлы'),
        ),
    ]
