# Generated by Django 3.2.9 on 2022-01-20 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0005_alter_calculate_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Укажите справочную цену материала', max_digits=7, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Справочная цена материала'),
        ),
    ]
