# Generated by Django 3.2.9 on 2022-01-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0006_alter_material_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quantitymaterial',
            name='unicue_material',
        ),
        migrations.RemoveConstraint(
            model_name='quantitywork',
            name='unicue_work',
        ),
    ]
