# Generated by Django 3.2.9 on 2022-01-30 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estimate', '0007_auto_20220128_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculates', to=settings.AUTH_USER_MODEL, verbose_name='Автор расчета'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='material',
            field=models.ManyToManyField(related_name='calculates', through='estimate.QuantityMaterial', to='estimate.Material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='tag',
            field=models.ManyToManyField(related_name='calculates', to='estimate.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='work',
            field=models.ManyToManyField(related_name='calculates', through='estimate.QuantityWork', to='estimate.Work', verbose_name='Виды работ'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='calculate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='estimate.calculate'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quantitymaterial',
            name='calculate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_materials', to='estimate.calculate'),
        ),
        migrations.AlterField(
            model_name='quantitymaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_materials', to='estimate.material'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='calculate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_works', to='estimate.calculate'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_works', to='estimate.work', verbose_name='Наименование работ'),
        ),
    ]
