# Generated by Django 3.2.9 on 2022-02-02 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0010_alter_quantitywork_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitymaterial',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='quantitymaterial',
            name='price',
            field=models.IntegerField(blank=True, default=0, help_text='Укажите цену материала', null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Цена материала'),
        ),
        migrations.AlterField(
            model_name='quantitymaterial',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, help_text='Укажите колличество материала', null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Колличество материала'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='price',
            field=models.IntegerField(blank=True, default=0, help_text='Укажите цену работы', null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Цена за работу'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение: 1')], verbose_name='Колличество'),
        ),
    ]
