# Generated by Django 3.2.9 on 2022-02-02 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0011_auto_20220202_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='fuel_price',
            field=models.FloatField(help_text='Затраты на транспорт', validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Транспортные расходы'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.FloatField(blank=True, default=0, help_text='Укажите справочную цену материала', null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Справочная цена материала'),
        ),
        migrations.AlterField(
            model_name='quantitymaterial',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='quantitymaterial',
            name='price',
            field=models.FloatField(blank=True, default=0, help_text='Укажите цену материала', null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Цена материала'),
        ),
        migrations.AlterField(
            model_name='quantitymaterial',
            name='quantity',
            field=models.FloatField(blank=True, default=0, help_text='Укажите колличество материала', null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Колличество материала'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='price',
            field=models.FloatField(blank=True, default=0, help_text='Укажите цену работы', null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Цена за работу'),
        ),
        migrations.AlterField(
            model_name='quantitywork',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение: 1')], verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.FloatField(blank=True, default=0, help_text='Укажите справочную цену за работу', null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение: 0')], verbose_name='Справочная цена работы'),
        ),
    ]
