version: '3.8'
services:

  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    image: akirosan/estimate
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      # - nginx_conf:/code/nginx/
    depends_on:
      - db
    env_file:
      - .env
    command: gunicorn calculate.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/
      - static_value:/var/html/static/ # В nginx/default.conf location /static/ {root /var/html/;} наверно
      - media_value:/var/html/media/ # В nginx/default.conf location /media/ {root /var/html/;} наверно
      # - ./frontend/build:/usr/share/nginx/html/
      #- ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      #- ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value:
