# Generated by Django 3.2.9 on 2022-01-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True, help_text='Не стесняйтесь, расскажите о себе', max_length=500, verbose_name='Биография'),
        ),
    ]
